### ISSUE TITLE
 Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?

### ISSUE THREAD

**Issue by chhenning** [HazyResearch/fonduer-tutorials#1]
On Ubuntu 18.04 before installing the requirements, I think, you need to also install the libxml2 libs via:
`sudo apt install libxml2-dev libxslt1-dev`

**Comment by lukehsiao** [comment]
Thanks, we haven't tested with Ubuntu 18.04 yet, so this is helpful!

**Comment by lukehsiao** [comment]
Confirmed that this is the case in Ubuntu 18.04. This is a requirement for `lxml`, which is one of our dependencies [[1]](http://lxml.de/installation.html). Alternatively, you can also install `sudo apt install python3-lxml`.
