### ISSUE TITLE
ImportError: cannot import name 'HTMLPreprocessor'    ==(maybe OmniParser also)

### ISSUE THREAD

**Issue by SeekPoint** [HazyResearch/fonduer-tutorials#10]
(.venv) mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ PYTHONPATH=../../ python3 max_storage_temp_tutorial.py 
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[INFO] fonduer.meta - Connecting user:postgres to stg_temp_max:5432
[INFO] fonduer.meta - Initializing the storage schema
Traceback (most recent call last):
  File "max_storage_temp_tutorial.py", line 86, in <module>
    from fonduer import HTMLPreprocessor, OmniParser
ImportError: cannot import name 'HTMLPreprocessor'

**Comment by lukehsiao** [comment]
Please use the latest tutorial code at [fonduer-tutorials](https://github.com/HazyResearch/fonduer-tutorials). You are using Fonduer v0.2.3, but using the old syntax. In this case, it's been renamed to `HTMLDocPreprocessor`.
