### ISSUE TITLE
ImportError: No module named 'fonduer.parser.preprocessors'

### ISSUE THREAD

**Issue by clayms** [HazyResearch/fonduer-tutorials#11]
When running the following line from `max_storage_temp_tutorial.ipynb` :

`from fonduer.parser.preprocessors import HTMLDocPreprocessor`

I get the following error:

`ImportError: No module named 'fonduer.parser.preprocessors'`

The following runs successfully, so I know fonduer is installed.
```
from fonduer import Meta
session = Meta.init(conn_string).Session()
```

**Comment by lukehsiao** [comment]
Are you using fonduer v0.2.3?

**Comment by clayms** [comment]
I used `pip install fonduer` which I see only has up to `0.1.8`.  I cloned this repo and am now putting everything in the `site-packages/fonduer/` folder.

**Comment by clayms** [comment]
This should also work
`pip install git+git://github.com/HazyResearch/fonduer.git`

**Comment by lukehsiao** [comment]
I see, it looks like you are using an old version of Python. The latest versions of fonduer only support Python 3.6+.

**Comment by clayms** [comment]
I just saw that.  Updating now.
