### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by clayms** [HazyResearch/fonduer-tutorials#13]
When running the following code cell from max_storage_temp_tutorial.ipynb on the data downloaded with `hardware/download_data.sh`, 

```
corpus_parser = Parser(structural=True, lingual=True, visual=True, pdf_path=pdf_path)
%time corpus_parser.apply(doc_preprocessor, parallelism=PARALLEL)
```

the following error ocured:

```
Process ParserUDF-3:
  File "/home/user/.venv/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
UnicodeEncodeError: 'ascii' codec can't encode character '\uf0b7' in position 9030: ordinal not in range(128)
```

The same general error repeated 3 more times for `'\uf0b7'` (2 more) and `'\u2014'`.

**Comment by senwu** [comment]
Hi @clayms,

Your issue may be related to this: https://github.com/HazyResearch/fonduer/issues/101.
Can you share us more information about your environments?

Thanks,
Sen

**Comment by clayms** [comment]
Thanks @SenWu  that was exactly the problem I was having.  Everything is working now.
