### ISSUE TITLE
OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by clayms** [HazyResearch/fonduer-tutorials#14]
On the Postgresql install for Ubuntu, even after I modified the `pg_hba.conf` file, I still had to change the connection string from:

```
conn_string = 'postgres://localhost:5432/' + ATTRIBUTE
```

to:
```
conn_string = 'postgres:///' + ATTRIBUTE
```

then everything worked.

In case anyone else runs into the same problem.

**Comment by EduardoDeLima** [comment]
Another thing that worked for me was changing pg_hba.conf adding:
host	all		all		127.0.0.1/32           trust
host	all		all		::1/0			       trust

**Comment by lukehsiao** [comment]
In case anyone else stumbles upon these, these are good options. We have a few more listed in our FAQs: https://fonduer.readthedocs.io/en/latest/user/faqs.html#how-do-i-connect-to-postgresql-i-m-getting-fe-sendauth-no-password-supplied
