### ISSUE TITLE
Tutorial Data available?

### ISSUE THREAD

**Issue by chhenning** [HazyResearch/fonduer-tutorials#2]
Is the data available on you server? For instance:

http://i.stanford.edu/hazy/share/fonduer/paleo_tutorial_data.tar.gz

**Comment by lukehsiao** [comment]
The download_data.sh scripts provided with the tutorials will download the data.

**Comment by chhenning** [comment]
This is what I get when executing the download_date.sh
```
chhenning@ubuntu:~/repos/fonduer-tutorials/paleo$ ./download_data.sh 
Downloading paleo tutorial data...
Can't timestamp and not clobber old files at the same time.
Usage: wget [OPTION]... [URL]...
Unpacking paleo tutorial data...
tar (child): paleo_tutorial_data.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Deleting tar file...
rm: cannot remove 'paleo_tutorial_data.tar.gz': No such file or directory
Done!
```

**Comment by lukehsiao** [comment]
@chhenning the data in the tar is correct, so we may just have a bug in the download_data script. ~~Which version of wget do you have?~~. I've pushed a fix. Feel free to test it out when you can, and thanks for submitting the issue!
