### ISSUE TITLE
Invalid link references: fonduer.readthedocs.io gives "page does not exist" error

### ISSUE THREAD

**Issue by nicholaschiang** [HazyResearch/fonduer-tutorials#25]
**Describe the bug**
In the Intro_Data_Model.ipynb, the links referencing fonduer.readthedocs.io give a "this page does not exist" error.

**To Reproduce**
1. Go to fonduer-tutorials/intro/Intro_Supervision.ipynb
2. Scroll down to the "Providing Supervision by Writing Labeling Functions" sub-section
3. Click on the "library of labeling function helpers" link referenced

**Comment by senwu** [comment]
Thanks for reporting this issue. The issue will be addressed in #26.
