### ISSUE TITLE
HTML data in Paleo Tutorial?

### ISSUE THREAD

**Issue by chintler** [HazyResearch/fonduer-tutorials#3]
I'm trying to follow [the tutorial notebook](https://github.com/HazyResearch/fonduer-tutorials/blob/master/paleo/formation_measurement_tutorial.ipynb)  and don't have the contents to 'project/data/html/' folder. I got the data from the tar file, and placed it in 'project/data/pdf/' Am I doing something wrong?

**Comment by lukehsiao** [comment]
The tar contains both a `pdf` and an `html` folder. Both should be placed in `project/data/`. You can just use the `./download_data.sh` script provided as well.

**Comment by chintler** [comment]
Thanks, I was using the bigger dataset.
Now, my PostgreSQL is exiting in cell 16, line 3 with error code 2- which means no data. I've checked the /tmp/ folder, and all the necessary data is present. Any pointers? I'm not opening a new issue because I'm not sure if this is my mistake.

**Comment by lukehsiao** [comment]
> Thanks, I was using the bigger dataset.

I'm not sure what dataset you are referring to.

> Now, my PostgreSQL is exiting in cell 16, line 3 with error code 2- which means no data.

Is there data in your `formation_measurement` database?

**Comment by chintler** [comment]
> Is there data in your formation_measurement database?

No, the error happens at insertion, from tsv -> psql. Attaching the error log. 
[error.txt](https://github.com/HazyResearch/fonduer-tutorials/files/1966078/error.txt)

Edit:
Any help on this? Or is there a mailing list I could refer?
