### ISSUE TITLE
End-to-End tutorial link is broke

### ISSUE THREAD

**Issue by mrmammadov** [HazyResearch/fonduer-tutorials#37]
I am trying to run the through tutorial in order to understand the Parsing process, but 'End-to-end' tutorial supplied in 'Intro_Data_model.ipynb' is not working

**Comment by lukehsiao** [comment]
This link works fine whether you are viewing on Github or in a jupyter notebook.

That is, the link is to `../hardware/max_storage_temp_tutorial.ipynb`. 

You can view the notebook on GitHub here: https://github.com/HazyResearch/fonduer-tutorials/blob/master/hardware/max_storage_temp_tutorial.ipynb
