### ISSUE TITLE
Please tag a version corresponding to Fonduer

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer-tutorials#46]
**Describe the bug**

The tutorial repository does not have any tags while Fonduer does.

**Expected behavior**

This repository also has tags like (0.5.0, 0.4.1) to be able to tell which commit is compatible with a certain version of Fonduer.

**Comment by lukehsiao** [comment]
Great idea. I will do so now.

**Comment by HiromuHota** [comment]
Thank you!
