### ISSUE TITLE
the function 'get_gold_labels' is missing in president_place_of_birth_tutorial.ipynb

### ISSUE THREAD

**Issue by hagen666** [HazyResearch/fonduer-tutorials#51]
**Describe the bug**
When I tried to run 'president_place_of_birth_tutorial.ipynb' in my own jupyter-notebook, an exception occurred in the In[26]:
L_gold_train = get_gold_labels(session, train_cands, annotator_name="gold")

After reading the source code, it should be:
 labeler.get_gold_labels(train_cands, annotator='gold')

**To Reproduce**
3. Execute the code '...'
If necessary, attach example data which can be used to replicate the issue.

**Expected behavior**

**Error Logs/Screenshots**
If applicable, add error logs or screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [Ubuntu 14.04]
 - PostgreSQL Version: [e.g. 9.6]
 - Poppler Utils Version: [e.g. 0.62.0]
 - Fonduer Version: [0.6.0]

**Additional context**

**Comment by senwu** [comment]
Thanks for pointing this out. This will fix in #50.
