### ISSUE TITLE
ImportError: cannot import name 'confusion_matrix'

### ISSUE THREAD

**Issue by NeuZcp** [HazyResearch/fonduer-tutorials#60]
**Describe the bug**
When I tried to run 'max_storage_temp_tutorial.ipynb' in my own jupyter-notebook, an ImportError occurred in the In _Phase 3: Probabilistic Relation Classification_    Loading Gold Data
from hardware_utils import load_hardware_labels. And it is cannot import name 'confusion_matrix'

After reading the source code, it should be:
from fonduer.learning.utils import confusion_matrix

**Error Logs/Screenshots**
Here is the Screenshots
[https://raw.githubusercontent.com/NeuZcp/issuePic/master/fonduerIssue.png](url)

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - PostgreSQL Version: 11.3
 - Poppler Utils Version: 0.41.0
![fonduerIssue](https://user-images.githubusercontent.com/26128531/59340846-5b8b0300-8d39-11e9-9ad3-eb2b5d9b5e4e.png)

 - Fonduer Version: 0.6.2

**Additional context**

**Comment by lukehsiao** [comment]
Thanks for reporting this. We made some breaking changes in preparation for the next version of fonduer (see https://github.com/HazyResearch/fonduer/blob/master/CHANGELOG.rst). We will be releasing that soon, and will update the version in the tutorial accordingly.
