### ISSUE TITLE
Is there a way to use someother Database(other than PostgreSQL) to store preprocessed data?

### ISSUE THREAD

**Issue by asoundarya96** [HazyResearch/fonduer-tutorials#7]

**Comment by senwu** [comment]
Hi @Soundarya1996,

Right now fonduer only supports PostgreSQL.
But for your question the answer is yes, it can support other databases as well. Fonduer uses SQLAlchemy to build database connection which supports many databases. More information can be found here: http://docs.sqlalchemy.org/en/latest/core/engines.html

**Comment by asoundarya96** [comment]
Thanks @SenWu.
