### ISSUE TITLE
Strip out from notebooks for easier Git operation and PR review

### ISSUE THREAD

**Issue by HiromuHota** [HazyResearch/fonduer-tutorials#70]
**Describe the bug**

This is not a bug, but a request to strip out cell outputs from notebooks.

The motivation is well written in https://mg.readthedocs.io/git-jupyter.html
> those cell outputs can be very annoying when using a version control system like e.g. Git. Whenever a change is made to a code cell, most likely the cell’s output will also change. The problem is that both changes will be shown in a “diff” view, but the (often much larger) changes in outputs will distract from the much more interesting changes in the code. This can make it very tedious to work on a notebook with multiple people.

**Expected behavior**

Use a tool like https://github.com/kynan/nbstripout to strip out cell outputs
1. Strip out cell outputs from the existing notebooks.
2. You can leave some of them by setting the `"keep_output": true` metadata on the cell.
3. Any future PR should follow this practice.

**Comment by lukehsiao** [comment]
I think there's no question stripping cell output makes it easier to track code changes. The original motivation for keeping the cell output in the notebooks is that that way, people can actually get a preview of the results without needing to actually run the notebook themselves. Thoughts, @SenWu?

**Comment by senwu** [comment]
Agree! We can some key output results if necessary but most of the output can be stripped out.
