### ISSUE TITLE
Tutorial fails during pickling of UDF object (AttributeError: Can't pickle local object 'create_engine.<locals>.connect') 

### ISSUE THREAD

**Issue by amtambe** [HazyResearch/fonduer-tutorials#86]
**Describe the bug**
During the Intro_Candidates tutorial, calling mention_extractor.apply(docs) resulting in an error:
AttributeError: Can't pickle local object 'create_engine.<locals>.connect'

**To Reproduce**
1. Run Intro_Candidates tutorial

**Expected behavior**

**Error Logs/Screenshots**
Stacktrace leads to the call to udf.start() in line 28 of fonduer/utils/udf.py

I tried wrapping udf.start() with a new function that just calls udf.start() (in line with https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function) but the same error occurs.

**Environment (please complete the following information):**
 - OS: MacOS 11.2
 - PostgreSQL Version: 14.6
 - Fonduer Version: 0.8.3
 - Python Version: 3.10.9

**Comment by amtambe** [comment]
Issue resolved by making a very simple code change that replaces the existing multiprocessing repo (which can't pickle local objects) with the improved pathos/dill/multiprocess version of this repo - it's directly substitutable. It requires installing the repo pathos (https://pypi.org/project/pathos/)

Code change:
In utils.udf.py, change replace "import multiprocessing..." with:
from pathos.helpers import mp
from multiprocess import Process as Process

Then change line 108 to "manager = mp.Managers()"

**Comment by quangzp** [comment]
I got Managers not found error
